"""add spotify account timestamps

Revision ID: 143b04ce81b7
Revises: d15b49202f55
Create Date: 2026-08-20 20:49:39.720328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143b04ce81b7'
down_revision: Union[str, Sequence[str], None] = 'd15b49202f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_accounts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('spotify_accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_accounts', 'updated_at')
    op.drop_column('spotify_accounts', 'created_at')
    # ### end Alembic commands ###
