"""add spotify sync logs

Revision ID: 2de74ae3fe1f
Revises: 143b04ce81b7
Create Date: 2026-08-22 14:44:40.792272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de74ae3fe1f'
down_revision: Union[str, Sequence[str], None] = '143b04ce81b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_sync_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('artists_synced', sa.Integer(), nullable=False),
    sa.Column('tracks_synced', sa.Integer(), nullable=False),
    sa.Column('history_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_sync_logs_status'), 'spotify_sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_spotify_sync_logs_user_id'), 'spotify_sync_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spotify_sync_logs_user_id'), table_name='spotify_sync_logs')
    op.drop_index(op.f('ix_spotify_sync_logs_status'), table_name='spotify_sync_logs')
    op.drop_table('spotify_sync_logs')
    # ### end Alembic commands ###
