"""create initial music intelligence schema

Revision ID: d15b49202f55
Revises: 
Create Date: 2026-08-20 19:31:04.716412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15b49202f55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('spotify_artist_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_index(op.f('ix_artists_spotify_artist_id'), 'artists', ['spotify_artist_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('albums',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('spotify_album_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_spotify_album_id'), 'albums', ['spotify_album_id'], unique=True)
    op.create_table('spotify_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=1000), nullable=False),
    sa.Column('refresh_token', sa.String(length=1000), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('favorite_mood', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_spotify_track_id'), 'tracks', ['spotify_track_id'], unique=True)
    op.create_table('listening_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listening_history_played_at'), 'listening_history', ['played_at'], unique=False)
    op.create_index(op.f('ix_listening_history_track_id'), 'listening_history', ['track_id'], unique=False)
    op.create_index(op.f('ix_listening_history_user_id'), 'listening_history', ['user_id'], unique=False)
    op.create_table('track_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_features')
    op.drop_index(op.f('ix_listening_history_user_id'), table_name='listening_history')
    op.drop_index(op.f('ix_listening_history_track_id'), table_name='listening_history')
    op.drop_index(op.f('ix_listening_history_played_at'), table_name='listening_history')
    op.drop_table('listening_history')
    op.drop_index(op.f('ix_tracks_spotify_track_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('user_preferences')
    op.drop_table('spotify_accounts')
    op.drop_index(op.f('ix_albums_spotify_album_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_artists_spotify_artist_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
